### ISSUE TITLE
Standing next to cart throws errors

### ISSUE THREAD

**Issue by Moj-FPS** [michaelpipkin/PipValheimMods#1]
I'm having a weird bug where standing near a cart results in the log being spammed with the following:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::AutoPickup>(Player,single)
(wrapper dynamic-method) Player.DMD<Player::FixedUpdate>(Player)

Do you have any idea what could be causing this?

Thanks!

**Comment by michaelpipkin** [comment]
Other than spamming the Unity log, does the mod still prevent auto-picking up unwanted items?

**Comment by Moj-FPS** [comment]
Yes, it seems to be working fine other than the log spam.

**Comment by michaelpipkin** [comment]
I just published update 1.0.8, which should resolve this issue. It should become available from Thunderstore shortly.

**Comment by michaelpipkin** [comment]
@Moj-FPS - I plan to close this issue within the day, unless you have any other concerns. I have installed the latest version (now 1.0.9) in my game, and I don't get the errors anymore when next to a cart, but the rest of the functionality works as before.

**Comment by Moj-FPS** [comment]
That was the only concern. Thank you!
