### ISSUE TITLE
Pip.AutoPickupIgnorer.cfg location?

### ISSUE THREAD

**Issue by ZeeRabbit** [michaelpipkin/PipValheimMods#2]
I can't find the config file mentioned in the mod description. Can you point me to it?

**Comment by michaelpipkin** [comment]
@ZeeRabbit - it depends on whether you used Thunderstore Mod Manager to install the mod or you installed it manually.
If you used Thunderstore, it should have created a directory for you to store and manage your mods and config files. By default it is at:

C:\Users\\[username]\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\\[profile name]\BepInEx\config

If you downloaded the mod manually, then the config file should be in your Valheim game folder. For example, if you use Steam to play Valheim, by default, it would be something like:

C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\config

Either way, the config file is inside a BepInEx\config folder, so if you have some non-standard installation of Valheim or Thunderstore Mod Manager and you can't find the config file at either of the paths above, you can always search your computer for BepInEx.

Also, just a reminder - the config file is only created once you have launched Valheim at least one time with the mod installed.

Please let me know if this helps!

**Comment by michaelpipkin** [comment]
Closing this issue due to lack of response from submitter.
